name: lambda-deploy

on:
  push:
    branches:
      - main

jobs:
  deploy_source:
    name: build and deploy lambda
    strategy:
      matrix:
        node-version: [18.x]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.6.0
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3.5.1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install dependencies, Build application and Zip dist folder contents
        run: npm install && npm run build && cp package.json dist && cp -r ./node_modules dist && cd dist && zip -qr9 bundle.zip . && mv bundle.zip ..
      - name: Copy to S3
        run: >
          aws s3 cp
          bundle.zip
          s3://${{ secrets.AWS_S3_BUCKET }}/
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
      - name: Upload from s3 to lambda
        run: >
          aws lambda update-function-code
          --function-name DiscordLoLEsportsScheduleBot
          --s3-bucket ${{ secrets.AWS_S3_BUCKET }}
          --s3-key bundle.zip
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
